### ISSUE TITLE
[Question] Changing the MID for the cfe apps

### ISSUE THREAD

**Issue by mVanSteen** [WindhoverLabs/yamcs-cfs#48]
Hello, is there a way to edit the message id (or packet id) for the different apps. The doc does seem to match the current version and I cannot find a config file.

Thank you for your help

**Comment by lorenzo-gomez-windhover** [comment]
Yes. However, those message ids have a dependency on the build to put it simply. So I highly recommend going through this documentation first:[https://github.com/WindhoverLabs/auto-yamcs](https://github.com/WindhoverLabs/auto-yamcs) in order to understand our workflow. It will take sometime, but once you get it you move fast. Not manual and error-prone definition files-- a simple YAML file that drives the config of your ground system. Go through those docs and reach out if you have any questions.

**Comment by mVanSteen** [comment]
Thank you very much I sure will do.
Thanks for the help
